services:
    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            #- ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "80:80"
        networks:
            - dspacenet
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    dspacenet:
        external: true
