{
 "title": "MCP-150 Dashboard",
 "description": "Dieses Dashboard visualisiert in Echtzeit den Produktionsprozess, indem es Daten aus verschiedenen Quellen aggregiert und ÃƒÆ’Ã‚Â¼bersichtlich darstellt. Mithilfe von AR und digitalen Zwillingen kÃƒÆ’Ã‚Â¶nnen relevante Produktionsparameter ÃƒÆ’Ã‚Â¼berwacht und analysiert werden.  Funktionen:  Synchronisierte Tooltip-Funktion fÃƒÆ’Ã‚Â¼r eine einfache Analyse von Zeitpunkten ÃƒÆ’Ã‚Â¼ber mehrere Diagramme hinweg. Darstellung von Live- und aggregierten Daten fÃƒÆ’Ã‚Â¼r wichtige MessgrÃƒÆ’Ã‚Â¶ÃƒÆ’Ã…Â¸en wie Spindeldrehzahl und andere produktionsrelevante Parameter. Benutzerfreundliche Visualisierungen zur Identifizierung von Trends und Abweichungen im Produktionsprozess. Dieses Dashboard soll die Entscheidungsfindung unterstÃƒÆ’Ã‚Â¼tzen und die Effizienz im Produktionsablauf steigern.",
 "time": { "from": "2024-10-24T05:00:00.000Z", "to": "2024-10-24T05:59:00.000Z" },
 "panels": [
  {
   "title": "Programmstatus",
   "type": "stat",
   "description": "Status des laufenden Programm",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"active_operating_mode\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      status: if r._value == 2 then \"Aktiv\" else string(v: r._value)\r\n  }))\r\n  |> yield(name: \"mean_active_operating_mode\")\r\n"
    }
   ]
  },
  {
   "title": "Aktivermodus",
   "type": "stat",
   "description": "Aktives Programm was aktuell Arbeit \n--> muss Manuel ausgewÃƒÆ’Ã‚Â¤hlt werden ",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"active_operating_mode\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._value == 2 then \"Auto\" else string(v: r._value)\r\n  }))\r\n  |> yield(name: \"mean_active_operating_mode\")\r\n"
    }
   ]
  },
  {
   "title": "Fehlermeldung",
   "type": "stat",
   "description": "Aktuelle Fehlermeldung",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"program_status\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._value == 0 then \"Keine Fehler\" else string(v: r._value)\r\n  }))\r\n  |> yield(name: \"mean_program_status\")\r\n"
    }
   ]
  },
  {
   "title": "Zykluszeit",
   "type": "stat",
   "description": "Zeigt die aktuelle Zykluszeit des Prozesses in Sekunden an",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "__auto",
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"cycle_time\")\r\n  |> last() \r\n  |> yield(name: \"current_cycle_time\") \r\n\r\n"
    }
   ]
  },
  {
   "title": "Restlaufzeit",
   "type": "stat",
   "description": "Restlaufzeit des verbleibenden Programm ",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "__auto",
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"remaining_time\")\r\n  |> last() // Holt den letzten verfÃƒÆ’Ã‚Â¼gbaren Datenpunkt\r\n  |> yield(name: \"current_remaining_time\") // Einzigartiger Name fÃƒÆ’Ã‚Â¼r das Ergebnis\r\n"
    }
   ]
  },
  {
   "title": "Einheit des Vorschub",
   "type": "stat",
   "description": "Geschwindigkeit mit der sich die Achsen bewegen",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"feed_unit\")\r\n  |> aggregateWindow(every: 1h, fn: mean)\r\n  |> yield(name: \"mean_feed_unit\")"
    }
   ]
  },
  {
   "title": "Poliermittel Temperatur",
   "type": "stat",
   "description": "ÃƒÆ’Ã…â€œberwachung fÃƒÆ’Ã‚Â¼r die Temperatur des Poliermittel",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "__auto",
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) // Nutzt den von Grafana vorgegebenen Zeitraum\r\n  |> filter(fn: (r) => r._measurement == \"temperature_polishing_agent_actual\")\r\n  |> aggregateWindow(every: 1h, fn: mean)\r\n  |> yield(name: \"mean_temperature_polishing_agent\") // Einzigartiger Name fÃƒÆ’Ã‚Â¼r das Ergebnis\r\n"
    }
   ]
  },
  {
   "title": "Arbeitsdruck ",
   "type": "gauge",
   "description": "Zeigt den Arbeitsdruck als Soll- und Istwert an",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"working_pressure_actual\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_working_pressure_actual\")\r\n\r\n  from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"working_pressure_setpoint\")\r\n  |> last()\r\n  |> yield(name: \"mean_working_pressure_setpoint\")"
    }
   ]
  },
  {
   "title": "Spindel Geschwindigkeit 1",
   "type": "gauge",
   "description": "Soll- und Istwert der Geschwindigkeit der ersten Spindel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"spindle_1_speed_setpoint\")\r\n  |> last()\r\n  |> yield(name: \"mean_spindle_1_speed_setpoint\")\r\n\r\n  from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"spindle_1_speed_actual\")\r\n  |> last() // Holt den letzten verfÃƒÆ’Ã‚Â¼gbaren Datenpunkt\r\n  |> yield(name: \"current_spindle_speed\") // Einzigartiger Name fÃƒÆ’Ã‚Â¼r das Ergebnis"
    }
   ]
  },
  {
   "title": "Spindel Auslastung 1",
   "type": "gauge",
   "description": "Auslastung der ersten Spindel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"spindle_1_utilization\")\r\n  |> last()\r\n  |> yield(name: \"mean_spindle_1_utilization\")"
    }
   ]
  },
  {
   "title": "Position XYZ-Achsen",
   "type": "stat",
   "description": "Aktuelle Position der XYZ-Achsen",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"position_x_actual\" or r._measurement == \"position_y_actual\" or r._measurement == \"position_z_actual\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._measurement == \"position_x_actual\" then r._value + 150.0 else r._value\r\n  }))\r\n  |> aggregateWindow(every: 1m, fn: mean)  // Aggregiert Daten in 1-Minuten-Intervallen und berechnet den Durchschnitt\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\"])\r\n  |> sort(columns: [\"_measurement\"]) // Sortiert die Werte in der Reihenfolge der Achsen\r\n  |> yield(name: \"current_position\")\r\n"
    }
   ]
  },
  {
   "title": "Stromauslastung Spindel 1",
   "type": "gauge",
   "description": "Aktueller Stromverbrauch der ersten Spindel ",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"spindle_1_current\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_spindle_1_current\")"
    }
   ]
  },
  {
   "title": "Spindel Geschwindigkeit 2",
   "type": "gauge",
   "description": "Soll- und Istwert der Geschwindigkeit der zweiten Spindel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"spindle_2_speed_setpoint\")\r\n  |> last()\r\n  |> yield(name: \"mean_spindle_2_speed_setpoint\")\r\n\r\nfrom(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"spindle_2_speed_actual\")\r\n  |> last()\r\n  |> yield(name: \"mean_spindle_2_speed_actual\")"
    }
   ]
  },
  {
   "title": "Spindel Auslastung 2",
   "type": "gauge",
   "description": "Auslastung der zweiten Spindel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"spindle_2_utilization\")\r\n  |> last()\r\n  |> yield(name: \"mean_spindle_2_utilization\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Position AB-Achse",
   "type": "stat",
   "description": "Aktuelle Position der AB-Achsen",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"position_a_actual\")\r\n  |> aggregateWindow(every: 1m, fn: mean)  // Aggregiert Daten in 1-Minuten-Intervallen und berechnet den Durchschnitt\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\"])\r\n  |> yield(name: \"current_position_a_actual\")\r\n\r\nfrom(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"position_b_actual\")\r\n  |> aggregateWindow(every: 1m, fn: mean)  // Aggregiert Daten in 1-Minuten-Intervallen und berechnet den Durchschnitt\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\"])\r\n  |> yield(name: \"current_position_b_actual\")\r\n"
    }
   ]
  },
  {
   "title": "Stromauslastung Spindel 2",
   "type": "gauge",
   "description": "Aktueller Stromvrbrauch der zweiten Spindel ",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"spindle_2_current\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_spindle_2_current\")"
    }
   ]
  },
  {
   "title": "Auslastung",
   "type": "timeseries",
   "description": "Grafische Darstellung der Auslastung der verschiedenen Achsen ÃƒÆ’Ã‚Â¼ber die Zeit",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"utilization_x\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_utilization_x\")\r\n\r\nfrom(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"utilization_y\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_utilization_y\")\r\n\r\nfrom(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"utilization_z\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_utilization_z\")\r\n\r\nfrom(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"utilization_a\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_utilization_a\")\r\n\r\nfrom(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"utilization_b\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_utilization_b\")"
    }
   ]
  },
  {
   "title": "Stromauslastung",
   "type": "timeseries",
   "description": "Grafische Darstellung der Stromauslastung der Achsen und Spindeln ÃƒÆ’Ã‚Â¼ber die Zeit",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"current_x\")\r\n  |> aggregateWindow(every: 1m, fn: last) // Holt den letzten Wert jeder Sekunde\r\n  |> yield(name: \"all_values_current_x_per_second\")\r\n\r\n\r\n\r\nfrom(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"current_y\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_current_y\")\r\n\r\nfrom(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"current_z\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_current_z\")\r\n\r\nfrom(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"spindle_1_current\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_spindle_1_current\")\r\n\r\nfrom(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"spindle_2_current\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_spindle_2_current\")\r\n\r\nfrom(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"current_a\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_current_a\")\r\n\r\nfrom(bucket: \"mcp150-opcua\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"current_b\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"mean_current_b\")"
    }
   ]
  },
  {
   "title": "Start/Stop Service",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  }
 ]
}