CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE USER dspace WITH PASSWORD 'dspace' NOSUPERUSER;
CREATE DATABASE dspace;
GRANT ALL PRIVILEGES ON DATABASE dspace TO dspace;
ALTER DATABASE dspace OWNER TO dspace;

\c dspace;
CREATE EXTENSION IF NOT EXISTS pgcrypto;