{
 "title": "Übersicht AG-Bliedtner [HOME]",
 "description": "Startseite",
 "tags": [
  "Startseite",
  "Home",
  "Übersicht",
  "Menu"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Raspberry PI (10.130.0.135)",
   "type": "stat",
   "description": "AF 34 (04.00.34)",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status\nFROM state\nWHERE\n  $__timeFilter(timestamp) AND\n  names_id = 100\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Raspberry PI (10.130.0.144)",
   "type": "stat",
   "description": "DMG Ultrasonic 20 linear",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status\nFROM state\nWHERE\n  $__timeFilter(timestamp) AND\n  names_id = 102\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Raspberry PI (10.130.134.255)",
   "type": "stat",
   "description": "HM.500",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status\nFROM state\nWHERE\n  $__timeFilter(timestamp) AND\n  names_id = 103\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Raspberry PI (10.130.0.17)",
   "type": "stat",
   "description": "Festo",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status\nFROM state\nWHERE\n  $__timeFilter(timestamp) AND\n  names_id = 104\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Raspberry PI (10.130.0.57)",
   "type": "stat",
   "description": "Raspberry PI DMG (2) KSS",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status\nFROM state\nWHERE\n  $__timeFilter(timestamp) AND\n  names_id = 106\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Raspberry PI (10.130.0.218)",
   "type": "stat",
   "description": "Raspberry PI Teeküche",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status\nFROM state\nWHERE\n  $__timeFilter(timestamp) AND\n  names_id = 107\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Raspberry PI (10.130.0.226)",
   "type": "stat",
   "description": "Raspberry PI SLA",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status\nFROM state\nWHERE\n  $__timeFilter(timestamp) AND\n  names_id = 105\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Raspberry PI (Robocam)",
   "type": "stat",
   "description": "Raspberry PI Robocam (TV- 32)",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status\nFROM state\nWHERE\n  $__timeFilter(timestamp) AND\n  names_id = 109\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "OPC-UA Server (10.70.2.6)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status\nFROM state\nWHERE\n  $__timeFilter(timestamp) AND\n  names_id = 1001\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Datenbankserver (10.70.2.4)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status\nFROM state\nWHERE\n  $__timeFilter(timestamp) AND\n  names_id = 1000\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Datenbankserver2 (10.70.16.69)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status\nFROM state\nWHERE\n  $__timeFilter(timestamp) AND\n  names_id = 1003\nORDER BY timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 2 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n<br \\>\n<p>\n\n\n<p>\n<p>\n<font size=6em>\n  <span>Dashboards AG-Bliedtner</span> <p> \n  <!--<img src=\"https://ag-bliedtner.de/images/logo.png\"> -->\n  </font>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n<br \\>\n<p>\n\n\n<p>\n<p>\n<font size=6em>\n  <span>Dashboards Extern</span> <p> \n  <!--<img src=\"https://ag-bliedtner.de/images/logo.png\"> -->\n  </font>\n</div>"
   }
  },
  { "title": "Allgemeine Dashboards", "type": "dashlist", "gridPos": { "h": 25, "w": 4, "x": 0, "y": 7 } },
  { "title": "Maschinen und Anlagen", "type": "dashlist", "gridPos": { "h": 26, "w": 4, "x": 4, "y": 7 } },
  { "title": "Labore und Räume", "type": "dashlist", "gridPos": { "h": 16, "w": 4, "x": 8, "y": 7 } },
  { "title": "Demonstratoren", "type": "dashlist", "gridPos": { "h": 16, "w": 4, "x": 12, "y": 7 } },
  { "title": "Deaktiviert", "type": "dashlist", "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 } }
 ]
}